

## Interests

* Computational Biology
* Evolutionary Biology
* Genetics

## Projects

As an undergraduate researcher in Rob Carey's lab at Lebanon Valley College, I helped [elucidate the evolutionary history](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3680112/) of expansins in the lycophyte *Selaginella moellendorffii*. 

Following graduation I received a post-baccalaureate intramural training award (IRTA) to work in the lab of Stephen Leppla at the National Institutes of Health (NIH) in Bethesda, Md. Here I worked on projects related to protein production and [genome engineering](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0183346) using an avirulent strain of *Bacillus anthracis*.

In 2014, I joined Dan Cosgrove's lab at Penn State University, again focusing on expansin evolution. I have worked on several projects during graduate school, including:

* *in vitro* evolution of cellulose binding module 63 using phage display
* Evolution of the *Spridoela polyrhiza* (Greater Duckweed) expansin superfamily
* Targeted knock out of expansin genes in *Arabidopsis thaliana* by CRISPR/Cas9


