---
title: "Nate Hepler's website"
output: 
  html_document:
    theme: spacelab
    toc: true
    toc_depth: 3
    toc_float: true
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About

Working on my PhD  at Penn State University, majoring in Plant Biology. Recently I have developed an interest in computer science and computational biology, which has begun to shape both my current research and future aspirations. 

## Interests

* Computational Biology
* Evolutionary Biology
* Genetics

## Projects

As an undergraduate researcher in Rob Carey's lab at Lebanon Valley College, I helped [elucidate the evolutionary history](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3680112/) of expansins in the lycophyte *Selaginella moellendorffii*. 

Following graduation I received a post-baccalaureate intramural training award (IRTA) to work in the lab of Stephen Leppla at the National Institutes of Health (NIH) in Bethesda, Md. Here I worked on projects related to protein production and [genome engineering](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0183346) using an avirulent strain of *Bacillus anthracis*.

In 2014, I joined Dan Cosgrove's lab at Penn State University, again focusing on expansin evolution. I have worked on several projects during graduate school, including:

* *in vitro* evolution of cellulose binding module 63 using phage display
* Evolution of the *Spridoela polyrhiza* (Greater Duckweed) expansin superfamily
* Targeted knock out of expansin genes in *Arabidopsis thaliana* by CRISPR/Cas9

## Professional Training

1. **Teaching Physical Computing with Raspberry Pi and Python**
    * FutureLearn online course, June 2018
    * Description: Four-week introductory course on Raspberry Pi and Python. Focus on using programming as a teaching tool.

2. **The Complete Python Course. Learn Python by Doing**
    * Udemy online course, September 2018
    * Description: 27.5-hour intensive course on the Python programming language. Content includes basic concepts, object oriented programming, databases, web scraping, and web development.

3. **Biostatistics for Big Data Applications**
    * edX online course, University of Texas Medical Branch, October 2018
    * Description: Eight-week course covering fundamental biostatistical methods with a focus on analyzing and visualization data using R.

4. **Chromebook Data Science (CBDS)**
    * Leanpub online course, Johns Hopkins University, October 2018
    * Description: 12 course set designed to educate anyone with a computer on the basics of data science. A particular focus is placed upon less expensive methods for performing data analysis (e.g., Chromebook).

## Profiles

- [LinkedIn](https://www.linkedin.com/in/nathankhepler/)
- [GitHub](https://github.com/nkhepler)
- [Twitter](https://twitter.com/nate_hepler)
- [Blog](https://nathanhepler.wordpress.com)
- [Penn State](https://www.huck.psu.edu/people/nathan-hepler)

## Contact

- nkh117 [at] psu [dot] edu
- nkhepler001 [at] gmail [dot] com
